apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - cloudflared/ks.yaml
  - cloudflareddns/ks.yaml
  - external-proxmox/ks.yaml
  - flaresolverr/ks.yaml
  - home-assistant/ks.yaml
  - mosquitto/ks.yaml
  - tailscale/ks.yaml
