apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+aeOV38974neCeMMqS8Ae1yU3qdxa/9fBGGFRDDeIaamoGMOOZuG6rPQSFG52g3uzX532IuGCVpVXqmueTJloLGEczNOUrGEAdzZPH+NgwzRWP3gi8ce3jEcH4AW/y6eVLIw5o0e5u8SJcLUBA2Rl7MxwSkkceqlb1nWt3QkYXCs+7ME6r/GJjdNkcvoW/mMdkrFZfeLssn/vPMWwc3Z7KZbL0CpfMG0itWzlrWv4tmkxrQHQPAoCIv1Wjhb7pxDtBr6XmULasjouJcX4S/0zWFtTlupUnfBsks7IQUJdWIaCZs6Q2wwNKwVkgXQ1dB/oMWp3uaR4u6xmkOOaAPgcl8BKop48apee57tk0ep80TIK+YgFH46L87wKi1NR+XJ,iv:XZrG47UO4hd5b8pqxoQvMTZ9seRt0W9/SrX9ZKu4kYo=,tag:b4H/8StdVk60ZIR4L40PYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:eHRb8ogqn7fNyz1rJNtPAf5E+02OoaUEWeP5EoUTFHjatZbT7JBdUM96iA77dXTt0ii75UDlhYm8IeGM/MA653QrbM86u5luDl01EW8+OmLL4ibXSFANGEQ81Lfd2S1TZFwY/f+ocDpaTlvw7tWp7VzNOCar2yz/H/nIvIet9jbApqVu77NenCLyXwnW0fzqOl0GCTw9qyO+FwFDsVfIr/zvZccPZYAAwfJaYqczDOP/aXLaBSkZV7cuEX1sgLIbtPYifBmo1HTts7zhlQ==,iv:6L6BUq151AbZxPfCrOqrAIdDTeIPY+gTdGNdBc97Myg=,tag:U48Ow+5PcNoBKXOTZGXVlg==,type:str]
    known_hosts: ENC[AES256_GCM,data:TWSmqRlUza2NsypzL46gtgj+qshNgi2OzU5lW59KVPu368s/X8BzPS+DPWBFIM0shWybpNB2kpqabjX+fJdcAsM505J8MCGbRjF1neb/YKvE4g7ne+iIj9wo9zHqHRa25U6QPQq+yXTFhXHwMLoXt9Sx5cyx1yAq73OfG3IfFW55LTb0Dh2BLJGgxiqMvbvOmlCmK4J+PO2PGda/CGs8wlyGmG11MD43uiVJ,iv:QjN7Pp9EPW76MQ+51biQKeS3SWPZcltah6TBdB6i5Zc=,tag:rY9LGRZZVTk26zrwwbzMWA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ01HbERuZ2NBZ3daaS8v
            K3lDOEphcTVuQmFPN1dvWk1sQmxIejRGYkZvCkpudVA2bnlOUXdoQjRrRFFVNDUw
            M1JMVHBaZUQxWGc4STZ1SFI4MVNQaW8KLS0tIDBoc0xEOGZ5MExudFN5NTF6dE4v
            dUJubzFyYVZobi9WTW1mSXM0V0wrTlEKJ9wz5qW4qHupZzSoMGJJfEdv7NAIqOU5
            x+f2t8zyuk7hp0n93xHHlFgqke+NXV1EBQqwoau/FNkRO6VMq7s5aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T20:37:22Z"
    mac: ENC[AES256_GCM,data:zK6F+LZitKADkgRiBtXNxMCkPQoaPdJi+08gIiksR6wQ1wa1+6i0yzVJQuDQqPkcmnXQJ5KPxOr2OkaNPt3LfU9Thzdws6nkbTZEi7lu9KrjrGOsB3d7Uhmtj8xbUTorQF82nLqdrBFsP31U0ldMHxsTb8eA26rG1isScX86yb4=,iv:bMHKoJbF2qjdlJslcEEXiSsGeWuqeLxrlIoTxWF5s/c=,tag:Nxc06PMaYetoiM9vrXtnbg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
