apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UdPTpb6yxGujMPG7Dq8UdKsag5wsBOoNNWU2VulJ5BHzAnH6YauFyjVXUbeP2AX8VoikOe7VAZ81rh7hGCGQ6HiaMpc7lEx8YvIqlFcBQtuV4vPjP02METCl7sNg+vmMEIF6ZcJBmHMnNO9nu4WVdZBL4lnnxg725NIAabJ3Tm+dtN4FG4FDqr0w2NJ1DTM5bOsueSuOrUYKmE/uwXdBVdeTrhjB8FVQIjwZU9O2jjuAoxfxn8sWILDNSJyBbTWT9pshTbZc2q6Jo5YVxcPgvDZ3O6ilzGwhBW2pSeWpEf7YHvAAAWzuSFSOoWFO1Bt2VFweLMj85fQUIGUy8S+zIl1M7Q8dSDnKHy23uSIu8sdWc+eOwn2jRKWqxjgGjWKF,iv:PPejLIJ1/UfMRP2N1LloZ2/drhSzOqu2icYbR41o8dQ=,tag:O6B2Da4WOTbzZDVWPl/P+A==,type:str]
    identity.pub: ENC[AES256_GCM,data:JkX8bA5hMnSDrE9oKuF8QouIQXm+HlmKPv8vCF1mYE5yhKMneYT/7xSRe7pU/HLC2ARgFtwSKyGspB/BQpaav9rK5uyQoun46A0kSOEAuAzNyihPFm+4diJf76w4fs3bT4puaTFDPdP79a5mFJbt1FHFrA/KFaWtfFUo7by/b7tRVphOc18vu0xod/hH2Scoa9fS+Jm1n6TAbTr2sYr9CBKzpvH70Il/vEEsiQjen4IiDey8osghbe827UUYwEo9wuW5zTkdqrkj7nUd9Q==,iv:zvOt/O1iliEbf6nGsSmrw6E7UL4QCk1J5rmVadIlDIo=,tag:rl/vAk43isjE2lYc8ksGng==,type:str]
    known_hosts: ENC[AES256_GCM,data:/8W1gFF5xU7t3h2AB8ipo8dU+3T4/3OYeGN3Y7hYSMdweCEkdxjipsb/gLLdg1HrwM/q89IdFNSw4WcwxubFoCJ3mdKEU33Bhui1Eb+g5kuRefhamws0qahYNtknci9N3ncRv7/DG7K8bwT6V5KOQbqz1ZWdwwxHbnDcxl8TlxpuWrG92f4HCdVeEU2IRI+Z4qURhL1pdWBmCOBWIj0F0mB0U5vj3pGe/iH9,iv:vVtTer5eILSkBjZzsehkjYfHFgTCs/Q+VYbqsGld6VY=,tag:d03hmN7BlEmlAyEtvN/g0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTWFwNnZacmh5WGRuV2JY
            cG51cThMNVpNWXlDd0hncVpncy8xdUFxNEdVCmh3MEZmNk5Nck9iVVBnK1dTcklt
            RE1KWXgxUGZTQmZHNWtFa2NZVDc1MEkKLS0tIEZaY09mZkhsWEE5MGVlMkVwSUxz
            bkhWRlRJeG1DQ1liRG52ZmMvT3Q0TzgKi12bUWwbxRV0Fmo3yOAsHtCsF2LCs22Y
            02QbyBOS9UjIpUPNL4DMKCPSxKp+ztK39lo8WNn6IFQ4uBrBzFC7JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T21:49:22Z"
    mac: ENC[AES256_GCM,data:fEGYC6/7Bo+k2t5qJXB914V9WfOdcxk7VaKECskh/acqZ5hHZXnVq9xcJpxDwaFGQaw/r2dv7SzbPazbR0iuS9L6IwSVc6aMivSttq2NbuKURBo1ubmnSHz8ffw9PYTpnOsO8ZQ+yu09/dpHCgAWjYfFKKq/sS0MozHqXVFrdAk=,iv:0FSNV2DsbojmPPvtssJcRB1HG34LJn5vbV1VvJrLwJk=,tag:uV7YFv1+7CPeIRyDSaB4Bg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
