apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dnl6uXlhjfyk+/ummqSYKdMyInbgjbs3WHCkyF7UN3/Bd9QZDCCcuW+VKt24PGF3ytPgKsMxGn+6i+eX9b4WAuUBE98ktFISpQTeUNfM1qSqg2tSlTO3jUbdzf+zud64Xrh7G4DZfe4vwOegq9Fj++hyjQe9lDIocdfUHtJmsSF6eCCEfNtbA+UTzgygI4mVzjcqhtYpDevJDGXyjw/zmhxblPjaUHLmHeI+8aNNf8ILc10OHPKDDUspMTH0m8zLBlTrUPgNnZm5YXPDEoxo+GykHZjuV2iobSiuHj0RsbSOXlS1uWy0731FQsSYbLN9ZQUe0P4Ci2JowytODfuuE963m/VoB3d2SUlCnOUxPlbYjLqUtqqFiZUtA/FQczK6,iv:Lwd3wprNH96UNZ9pnYnGLN7UHtR3n+V8Ylk6mRIhSi0=,tag:UK6COcuD7RMFAbkIyCj8DA==,type:str]
    identity.pub: ENC[AES256_GCM,data:fVLxpde/iZP+LD1pttzKcC3F7o5rd+P3cCoywlzJiVvY6YAZ4SgDckcN/drNtEzDxa64M76K+biU0W3jOkYpLd7mi52bJB3UCTUELCPMO6FiTJ/AEcQBPu3bpvqljgDvgb4XPxO7nmkgMzFnVluPcSBm/PN6EFdWzOWEhuelOA/SuuK5TaNcYr0gY0ROiinyYU11hBv5vmOtVXtI/A+LoNvhVLL9165t+w11IOkPtNIG8JmqhSrVcgVOcE92aseUgwggESC0yC95J37U5w==,iv:t+AUWZXNLVByQFeyXyLTUrK9mlbkoOYjq5CSusoKwPI=,tag:ARRn5UjxtjTu8wqVOesLcA==,type:str]
    known_hosts: ENC[AES256_GCM,data:C0B5UGBGulryvm04JHvF4R+c0UTuZ3z4A1CSojcUhIVJ4ZPqKJiKJD0hDBLkVaNEJxTE8ZkJgRJhFZcFVeYTOq3ryAOqln9znvG5hmp2+Aww56/ggH1ITZNi2mamcHYP0H42tA2qWIaoYHiAdpTmvdQxk6KCOuCEHymdyfdbCktQKXNSanXJWTKdOPxvGCaMmt7kAH34WfJ0M36DaIDqfkUBEmNSY78+KKSh,iv:iLOBGJ7/q2i9a9UOYhPzk0NL+Q5zyD5MFIx1vnJrxkg=,tag:wmRdMI5JAkI9FXUySEZ9cA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxalZNVGdNMy9GVkYxNDVK
            TmY2aXFXeTJzSnJDcG1ZbXpjeGJCcTVzWEFNCmZNK1Z4SUNxTWUyeUF3YUEzUG5U
            eXNNc0RVNUpZVkhFOCsxaFVaaVBYaWsKLS0tIEs4RVhnYTFTZ29wcHZtdFRacGl1
            bTFmMzBpZEpiWHZJOXVmRjVOcy96VncKnSqAz1Hzq4NXkzRlIYWnap6qfagD6te4
            PPs5d6FABnBjNkv4rZ41l+AEomSua3DqpKCMgwPTU2mITmUzxsfo4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T22:30:23Z"
    mac: ENC[AES256_GCM,data:XKL8D6RQvq3+LowZtzCz8405sPE/IBKwvRXolJoUybCx4KBq+LFQQ8CAzEOQaVgAb3v2nNTidwh3DZxih8sRRsCDzb0lmxj3tSj2nc1NQ8+kWdrgxtOeqthUkfKP6A4Yd5xy6xJY/guEyWrXePLj9Zql714Ot7B9oqB5d9qOH1c=,iv:9lsbmRcC53Ai5PwAkz33VlNTL0rX0b6XyAfeUS2zG8o=,tag:Du92SVtKN8dQ2//z0wVM0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
