apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xKN7ybiL2FLmSu9JEgHQmIx7+eMSa+P9Z1ohLId/It+Bbg+JocdR0bfVkej4rHqDkouMbDvEBjYuhF98t8fvGc0rKMVXp6M3Wi8n6GrYLVJHoD8sJFg43MkTjN1hFoA+MFDXdNmJjzyXWtX6HVPpUeVb5ft2mIOuZyzA2SrTWjvYgjPeCwQA0+sapTx/dLIUlB09yop6++cQoK+xm/qd+C5mwgm0zRKck0EPa7YF/7gYbL0smrM9kkAaoKA383rBiFW44GNgRkJjMlIbOJSuXHpYTynafXMlPRAO4KJn6JyXrwiMggCMppEfL9IWs+DXLJ+2wF94AT54KTBBGoPLpXqTYPuHT2rJQC0dZXDtxFo974Y1K1MFr6AdTYa+zSMY,iv:03fB3pH9VpJOQbSuPsM/mSM3iIi7FG+nULHg1J8g/DA=,tag:4zkYmW+2+7qdCAxlVOT1MA==,type:str]
    identity.pub: ENC[AES256_GCM,data:aOSqrP7ueUl8GuX8HXf1GhkgCnHs+5acX21IAmBQcvrSBq4uKxv1ebRM+VTYYnuL2428eei2BPo0mZcrOxBkmDJ3y3xTCNPfHhc+19UNRXyTIftcMRrgZZ5oRGz3oEc9fMuQiM1RkMSQgcypA+qK8b8Z8pWA8FaKPnL8/7SCK+Fbzfqei1KTcHY1JRAZXzIi6jM4Cobj/zmp+EVk4brVOqw7AyG81G3hpjkC7MUEhtoyC97f1m+ArbCojrjogB3WMxPpZ9qNnRULXQu8JA==,iv:SwIMrxKCqYiHCVpIkYXFI/8zFcSdYanW7BiqrVWtew0=,tag:S9624LSQPMZlf0W1/0ABZA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8FWfWxzogT0pOLbaxBMRAe6fMNl7jfcU37Eo/oLWkkjpV2V1KnmO3VRr69v6zHOtt4Yl1Ad5COoR/cFc9qWRlSneUS4cvkSN/hGyex6STzxwgcoLOfAWwYQAeXyv6DIK/ElbojnO2Q6MdcrS9bMbPWZXGQYnknv0jSkPTxWXHw1C227dGW9iwcUaChGm6vUJUDzQBOTXuIJEoWmPe0rPlWvwaX0yXI13pVU8,iv:TlOKvnmf8ODaOcyL7m1/CWRchkbEXTruw2yqHumKQOM=,tag:Z7GK1IF9pvQhuq9T4U+mbg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V09SOHgzYnhnQmt1ODdz
            UFUyMW82N0VidWNUNGk3djFuSW9NYzNtcDAwClFhZ1RTTWNIcHdKUVM4NzVvM1BS
            VmpzZnJScFMxWHdlWk90ZGdlVVhqVHcKLS0tIDdaaTlnb2NocUNyRERobW0vS253
            UU5qc1hYZmdiWVBFeG9wZnMvYzh1QlEK3D/+uW2LwSoAZQUKJSCAQiuSYCeFLIwR
            UzqCnyI2tldUtB19WRLKU+ITLnQTz2M5h4wz93mCMc8cW5JCL1rByQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T12:02:46Z"
    mac: ENC[AES256_GCM,data:QCB+RlNaQsZIxm2WDUK+Fb13uHqe+3gANWW+AdCpGeRf+QTAL09WbcyHBxWby65Uu0kzFpRblWIS0X50gfnu44ww+kq2Q1aLpnsjstk0BLF6Eq9lOkWjl5MGRUYD7kE8wG1qWyVT82b5IS7zJtT7kFUXbrHJnUUhYinLhzgnWjs=,iv:u6SJ9Mta5UQ706maBoiovAj37TsIlCZlIT4M7JhVyCE=,tag:8aVakMShxZDjo8hr+eEH/g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
