apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pT6SWjXlDoWhAtpVNv9UV9Dhu56CoPuL3zZan7IPlhCEqTT1AID80sQi/ZuL0k9FynADuMffoNx2nLONqhyh9bAEtImmr9FThfoKtm8WnLd0aGQMHOfUjF3/YjqVlEHBzPNEDcLVFOv0JxMp0HWblsFsjZXP6I/1D9e16eLHfsNhHysUb2M/d7FY6aseQj6hHtYibOom/oUm33+RM16LcDFhpj0VJWwpCaOMrHirfzENe7X4sWYwIrnbMyrGYg7a75UBU+gIn5Yy2+OQRfvYMI2eFRXqqJUyQ2NivJGY9pLiPL5SrXQuBKte7A2+Fxqei35n9X07E8QiNA5KhbtzInSbyIgtMtmHeIQsoXVUGc3sbob0+/AhHnJ6l4s+xUEL,iv:YPq3IfTkH80e4FGFXmDwls2XxmrlhphGKyZnDTK+hiY=,tag:orGVp5Avp3du3IVWy12GEQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:HoSUjoKxW0p+JuDMlzQavikdK264oO+Mo4T5qQbTiz5XGrypsebYE8+YSQ5r19mMb9edhVeVRqEfVJkoxXTG9KBiIDivwGKkm1+9uFZK+vsdlXpSOvsJDPGrGsl9NjH4qiefAKCJFxIMM9643rkglZcukXPPiSxGbeK7h55bCMM4DvaUkit6d/mAiGeKiTlQJ5LXQDOxl1o184bnDz/egHFJRPW9gTNnPF5hqtl/MEZ1kYo+IPrJqtOJwndDw7hM+4ARbiQswyDsvRZ3hw==,iv:us4sA9bSxKp7t5iu0RUo5W1Yy2BmZyaf3xED+PXwIP8=,tag:JrEMeaS4ZCkWMBBzdEEYzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:TjJOmMsjizkgjmUj1fnKpHKfF9rvb1OdzP+3ueytRfdAzaZUP8AkEIeFyfDUrH84YIe71U4tXBSlVjI0n37e4F4cqR7Gf+ogf0dNmZloXIcHM6wIp81IYBu11GsE0Cy4PetkoQUe3sAl/9TFdmfc6eEsgenTRivgizCT8UKIFEekj9rJiOVo7oQvy13hWW+vGHlSb6tkaYVyBSKtluBlQJWZM86NlSh2aKZQ,iv:pahwyGL5DyTX50PnjL4LR3zzv4jx7B1tHUWmDHMLZ48=,tag:VhhOYRKhMKQxtoZq0N/aBg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneGVoYVloc1V0VmhycGxJ
            V3NQNUhFdWQ0RUp6czFkWWVDdHR4Y3JEOEdRCkMrZEpHY2R0TnJVRzR5QnNWZ0VS
            M3N6Ym5HTWV3YnlyZGlrc3Q3enhxcEkKLS0tIHhKMU85cmZYM2FZelU1NUVhZGdl
            dllmMWllTEhSU0x2Q0VRSDNiWkh2UFUKWs7t0l1uZnA+W74sMDScIVuN40SkJEkC
            dQAo+tGRbO4kl/lFp1R8Dn10qnhwsfRXUmD89gFgfhN3nhshg7ar+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:55:06Z"
    mac: ENC[AES256_GCM,data:2aW0i6L+hsyAxM8zhZeVSJIB/a3eE5eIzTRMHRXFuDeGUw8M55+lqYgju8BrcPvx0iwQZE0eOJuPhhqTZf2072t0hknpmZJ/6HO2zziPxQUQo1nspOXg/wD+4aCK3Q1CHByPYNoOOWVjg32hBJRfkrLy2zZ0QEFs1qppUjXjCb0=,iv:v3PjTCYLvExfpKkqtZHf/YPuex2zlkERlrMnLoYYHYs=,tag:FA/Z6uJlW43kY/4PKhg3mA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
