apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IzKAoICR54FDBXuSJNhGcWafHTujwHFW+MWs5pVFi/ZogivsV8uOpAVywgUr2fXeikO0F0MI4Co+mDl7xkDdy9xD0H0EoJ5Uw53arJbNiaZrFEJjHpX2k+6LZ/3UmrQVKSJhV9pkL4wYJpStwDA2yldFCSbfxlrdMFBuv0BT8RX2ei88w/Jvy1dqZKJ3Yw36cai6TLkEF4asJbiFXeoxlC3NHI4GGC8MeKcjgAVXJzBF4SJZbfdfcrpf9DRtuL5gf9eaw5SU15QrB1cGYCQ0ZQwH+IIilFacrCvZn2uNmdMeZsoMo7AAqKVk+acA+5FZRPyuTe6EFeiS3CSKecOaM8Kjs8ZDOcl7hrloik7H1xR9cLVl6OZ6Ed3MU36b5Unr,iv:HisBrwCdneJev/y9kbjGVqXI+Wu6rHXcebKXDv5V0m8=,tag:qiE2LFzfjQkoor3fX/S2bg==,type:str]
    identity.pub: ENC[AES256_GCM,data:dJTZYfNGsrfEqIDuWFKKJX+wz+s0L++DL1J0cYg6i4oeAXoHwNT7WXXIvax5otPRuvXIKhXkhyZ8H1pV6ztnjy30/FhKw8m3jGy98E6ck35pgyFqahLvlSPs7a4FP+62E6mvxnAaxKdIa74EnIc0+xyQ590uLhf5Ov5mRM6rFFgxHZBCQZSM7xvfJ0WHAxMFH8YCsfl42JpHHoUszJAdUXh+qhDhb6vbQ55YyDXZ4IORFkJDPmoyxnEhEefXhzwHkPVAnshitDqSIJop6g==,iv:gNPKdgFNpLCTOMUdloJzuhjGYImPkWkz3lp5R5qQ8Zw=,tag:9XqPGMZeZA/F68L4YHiNPw==,type:str]
    known_hosts: ENC[AES256_GCM,data:LK8B4G5Ni/5xa7bS9VApfQna9aor1GRJWLJ7oHXFIVaSy9Sum4bljCxEQfvj16s2kAeN41ZvcBsXBsGdtywaRBHRYesFjHSaMw5bKSfeV9kLDImJtD6iZ5dwhaoK8zSC6PD6OPSMcw5ek7boeShoykAKiiMJQCMzHqbVGXPIhRG132CROH6dP1HmtxNgTmQ2h0vdoeIGx3dkF2eVmH7pIhZJeAObVLg2F+92,iv:/p7btVIUTA5j8D6/7vYcZ7m3MPF4LLiHJy6sAoXuLck=,tag:t3U5U0D3WSwbwqof4a32fg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdFFXa0lnQWszQU9NYUNq
            MXB6TkdLaW9rS0gzY050Nk92aWo5OGRVc3lRCi9zRWFyUWRkb04xTTBscEdwR00y
            SjFsaHYzczZjcVNSSStBRmxjN25PeDgKLS0tIFVwRW9HZE5KVkFFcVl3TVhrRXQ2
            VTlRZjBiYXozMG1OWHJyaHRqZEZDTlUKyXuK2UWBAAm6X2v3h9oXpwIw+LwcAQiC
            5bYUvdETzZlU+JDdyk1OeEfC5rPzbLysmikz+hj+fAUy1JnKIZoZKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T15:39:40Z"
    mac: ENC[AES256_GCM,data:5xU1c6KGA0sakz6yc1huVYH3OPa8Mth+66A2NMcK9gD9EDvD0w1zI6ICdftqacZKa5hpfpFWbEoU8nWxlB/YltVaH8btVRUzBEaVG16o2lBKWpuEmIRAabGdJqhDcWiOCBqXJw5AE9CxY2X188Jnv6iHDHDSqtomiOYHyaMR/UA=,iv:1NigPvJxv0xWOZTzrSXkafT5yo1Xhc+FzO06+cusI2k=,tag:9YXyjVDxf2KIZN+YwyhtdA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
