apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BJPXQ+euvM9Y0r08t4Q4tX2KhjQpA/XtgWI692PrWAdeB2foPoda2jQlFHKgWmiTWcFREORc2xuo0iLLTvUBUYWi+GMOHGuFSUWWGg7wE99Gk1+UEQAvfzOIcFbgPsu2JY0W8tGUPqV54rHzkZZ99fVnCfxUkBdJzNgmWwOqNCOweQjgr6p4jhSJgApTlJm2IoJ9UvwPb2jjanpAGcjW2dyDvr6J9oBfNBnmZGOie083hVaNA4RPM3t57wriRLiLiljdVlAsj/xGeD8kgDikwxjJLy2fwpbLI1GOrD++NRSAr2uPcpCCypYt+MrCasGSq+Tm8UQ3YMPbqgY6t1ow735z4ehCaKsALBINqwSIwOcGGETmL9sCwHUTQkog5N6f,iv:ZX5KSNPZEh8Z59WoO4nBLPsWhJGilnLKpqkXgW5XFLs=,tag:jk/ctIgJICU743DccQhI5g==,type:str]
    identity.pub: ENC[AES256_GCM,data:9GysiFrVEHVSoZLFOW/fP1cPe+9LQ494GGJ4Jc1NNoCyX/nPsDIxIUiotxY2PTTEiP39hfm20QJQtO6foAm0lNMIsgCv8Ut+81ujZutYbg5+kAo6KUofBt3lvp0RpwtWlBgZ109VZVArbEjjzrttEuBbS6Hh0aW2frz/siHY9DiKkUTgrXsZ9u1TCVVcEkot4/fhMX2sKI4z5Tnz20C8VQj08hF5OZU6pKxV8wv0ZZRJ0g64xLbfuzvI4oV96OB+6aShPCXRFHXFsFjvuA==,iv:w964S16UvEVLKs7wZOc/gjyLTWmGFEN+hL2CvCPjlFQ=,tag:rHH5nm2qCNnwRgM6JP4ahw==,type:str]
    known_hosts: ENC[AES256_GCM,data:9tD2JgPwAoCdw8HyC/QD42VBhG0R2jTarGJV1rM0g7P3Oxj6z9XKuzgKN3bm1yf97mblNRdwa50u6/WNWRxo0pc3mz3ND+mH1je4LceUne7QhGETTIYd4Sj4icHwfG78AuS8a3z/jg9zwBHu4lpUtJxEdLE5TCCmx8TCiBSVw3kwbtFsmYtW+GmXNRrrSKJKcC23Kph7igLzuxWVdOfrDVQ4liB1y+Gv5lAe,iv:GyZ7pCs5GKyPn2W+VEdE7PWkHE1b+mL+YyQof/SYDck=,tag:beEuvSAWFfNp+azgmf40sg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNFZCWDJXYWtPWFVGS280
            NTZNQ0FKcktuWFRPaTVKbHN1eEptejVRVmhFCmlrdTRIREJSNGUvWVhHVEo1MndO
            RVNaempTT0Z5d3NJc1RuWHU2Mk1RdDgKLS0tIGNDZmJ5UEpzcWdFaGlJVGJzMW1v
            SCs2eVZDTDBvcTRnaHBYZll2THVUbE0K9uOl59GWLilCEvDRiytCSdr+CwD8QBU6
            Ce2d57/RdtMzVYz3pV9o1sVJOgLuDdWMFIixZ1GghCyo33EhXaQsHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T22:08:01Z"
    mac: ENC[AES256_GCM,data:1TIGhROsVbTfbP+/kY0okvtdgWBjAyRTfSPtbj/1Khy1IDpOh8dTJ/lspZsQFaqvJ6XEi2h2ZOPQqqPSluIjhxW/IMltY7bQ8vWToRF/mmzHBQgAJ+X+WEs8Cjo5ysrRLDdeZo8irKv3jxv+3U0GXou2JRf2PyOdQo17LwsQcCo=,iv:lveqX9MK59P2zSS1ccsuWAs9bJCy4dh2oNC+boHXno8=,tag:FX/onno5355toSKU+AcHqQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
