apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SoPcsOXCdXkno0YDccLAD7T2hhSp7HDPSbtVuJfeWH0uEupIFwRNfoBzFB9JRnXatx3TPpnthfLjuzBsVnp5xG3ijTmBNsEHoDS1UCCtYVA0w7oa/mR0JFBLwwNQoRVvxJNuMcXk7+YndYuxq/y9cKXVswSIVQCLsy3RvqeFZwqRr6Jie8zy2hc/3/avYrKAmaNpp4guY8yBOIJw2x5LuWXZ60hWVoZAvYxbJ9d9FKPIaQdoCB0inbWsd4aMJxHu4bx8fKHuOPsaIIV29rtW2eXG2RBtHFoLjYlGgM9dcAK8Aj3l6whoT5slao3xTrQ2zzDeg7S30CBw4UQvLg4I0hmr0+aPgTfqoCQH89Q6O9GNjaqTKizDDmmo3WBrxB2z,iv:5MnI5NxT9Tb8VogvG1SRkT0QrSy4z7HZc8zXJaF/rTI=,tag:bWWv5l9vDYtVPQ4VUUb0Kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:OLLB/mDXJ87OgH8f5phJJyOLtMZLg6SAgyPwiMVf5bVCGAspnjwL6glnnXZSd4Cbrnvr70xHDnA6xl9J4xS+X8c6qNpyG2yMoTM6nynUPkGq1fIsG+BBu2xZlWgIysRNaJ0atyQf6Jkwb06jTkFnm+XwLzkbVbpQlvzvjnZt6Al+Dly8o6tjQypzayjUIAOj3c72MG5UwXYoNSAXtYW7k6Nq6psajjjvMR+T9k+fcM66FuwNEBLazMkkQi+M8Ff2060Trz5pGQlta5f6zQ==,iv:Z14xfJXpFFLHWZrVZ3EWClJsVtAmLH+5uT8DlmIRcdk=,tag:gDfmZbLp1Tj7acChiGxteA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ofqd+5pKCMr7ljhCg6P4MyN9JmOZb5da0KQFNQLlTSEWag9XXrd/QTgKY1C7TKzpx9ioonM28nHT9v/h24bTWfeWEAKp78o9raFCrpD0Ec0ULod8DETQ99lKPWLOhgDonyAtfmXI1yUfJvy3DV2LjK+XWFsVs9LkAa1HH3JvNItzO1Cwd8opv7mn3e+ITGkh5H+yNlyQ4N1dNjK11Ig1Q54yk2p3iRxMoIze,iv:khyGs38JRQlnicggh1ZYc6WOYPhoRarB7g7nGRJWFdo=,tag:elJmUmxB3Efht3knkw7lxQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eS9reTRzR2ZzMUp2UkV1
            UlhMRldPQmFrRDJRN0tKb2pKM3lQOWdxVUU4CmNIZTVySjkrL2ZaNTBrTllZMmdF
            OXVTWTdQdFIvK2FUNDZzWHhFUzE5REUKLS0tIDVOZmY3WE1sSk1zb0VDQUs3aTVT
            UTJHN1hhREFQMWZKT1ZXbzg0dGpsUUEK5QiFUzH3Rq88ghTG4RFO/iTr9vD+2dkw
            bnQdFA/HF7FMlLbdxKAO9+qkas6lLM+pnyr3bSN1dac0vhrTnUfNZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T17:01:51Z"
    mac: ENC[AES256_GCM,data:uwYDy9CIdxT65f+gjLbHGVbRL0V98n8ApCPcJhWnyZrBcvsd4JNT6JSFEUvxVdvHz1+hdZ75DFnfx71PHTjOth0MYEvSS6za5KIWIAqQJnj6YhgFO5M+22g/8A4/V7f9nSegqhs/NmP9YqCCx3NNfJyBhVaLS1HKEztEhVTVfwk=,iv:6/CFcNV48g0bKiEMiC+019wZrfzFDGl8F3LZX0mJDDA=,tag:ayTWFrUHKqxziCMYyPJvOQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
