apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WbSRHfwYbBSMszlw6RO/4okgyX6DxuVKfcmg0pPa5dglvIZdvvBqqea0zidXegRaNZ0HerKbsJpEYKUMoxDQLyF4tNRc+pYFjR4lRxl8afBDwBZNXFYcwzMGgFvguqwgdYe5cp/YF6qBtAA5zrH3PhW1a5OC0wb3WJB+7QqqcPAnhpLBbAIEbk5xfpj74bvUcNliGrmwldM+r+bqn9o1eZ/AmH6gUkFxz3ENgYqV72XzvvwpmwFkDK80gZNdYEMk7pNRa42IdgNSOu73JF7mDVRNOxV0bL0UlkPf5Ij+KB0ruRbCSpGkvO7RArgHjnlpNT9SccWpOpc6aem4As2p+heOyKzVRuo0dE4I7+6sF9X8XbZFViqMQ3bvFW2t4pVb,iv:e6ysovxAqIx23nMTh50daNw9WoDR5dWl+0DyJiz3vOA=,tag:+mJkDRDOy+3UR/bs2jVgaA==,type:str]
    identity.pub: ENC[AES256_GCM,data:p3rQcp2HvnT8zGlp5JrXHCKYoLBIsYnK2476QegE2vzZzg1L7xq3xrkKwCFrfKs3UHGrws+VLaNRd6A6EeF3mfQ9uDETbu8VLp417Lee1GlrqoDDvBMtOj295A3/G42CjUT1Z2gftmjEaBmWqQh2lPExIQoTAmyfkBtQ9uXEYUQo8tbxZ8ltcJCKG1WLNecIJ5NYzni7XRk3HYs0RHUec6H+tQmmdirY+/b7qL7jDIo4xYZfoTGvdObk2JQqaWuP/dHx3OQtmL2vb5G2EA==,iv:BXiYcOxdcZZXNPbOnvRkB6/xtvFEW9VdmJ7H7eZrNFM=,tag:AFBd9c6/PkXvL6wZUOkhmw==,type:str]
    known_hosts: ENC[AES256_GCM,data:btbXYXd90UdUkvSAhZJRqH0pWUv52MRjBWw9tnM8HRNh9E6eP/mcVNxUWj6AnYPx7qXYzrCYIgsHlxFvB26FucPNrf9PI7Vk+NVbyV2f0oc8mtEHR+dwtJ5jGzYIlYFVAFk4WZpmzfnu8YhIJ58yW8u4nZLBa7NWzgOo1bNxMYTTxBRH8fg9mEW7mq3S7xBaRVt1bzAgwe8umKCCO0IAAQOuFG/C9OQJLm23,iv:bzxG24vSFrV6KwtfUQHbZxYM7zHeiKci5Ed0SKFhQs4=,tag:uQNBd0D9XqhYpyGvttHBNA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbzVRZ20zczN0dmJ6NE9W
            T3NkLzRMQkRycGtad0VQYUNKRzF0NnN4eEVFCnQ5cUtaRlR3V3lvR2dXMXdwSGJ2
            dWpTenBIK1dpb3l5aEhweDgwM0o0VGMKLS0tIDVzSWlXQ1pPN0NhNFM4VFdOd2xj
            em9ZYWltbDd0aGxzeXFqQThSeGJhSFEKx83G1wNOl+cnDkHzkyeX2cJr1tzFaOVL
            1R95Kd9v9Z8qonkLRJN2FBlphzdiolxHGnebz038cfGhjepVZgMFWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T21:24:33Z"
    mac: ENC[AES256_GCM,data:WxlEegSyEo93eXI+jZUuwv5AuC/5qEZ9q040UOxmXS+UjW6YOcKTOR58HL41u/O3EqcCWy94A/fhUYe2pjAgUQSyKZ/N5XK5WHVOW0oGU8jrhWDiFGPAs1+iqwht6333Qb75oSnCY31tf7dpbli9gQ36q3iPWDqMpE+hf3oTVjw=,iv:wk4caUN+7K7hn8fjdPL3LiaD3IX2HgjKVS7L8aHpG3Y=,tag:8rBgOAflAqwi95kM9ye0jA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
