apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nOnB3aM8iyhuXpGCZ0PmbGutGYwYraVU8pOwbq+crKltv8bqz36o5I8vYO8TI8EUcwN6fMbTpC8fcUw8RUCCV/TZx+3ImQ/4CXAs4oqKtFE7qODtf9SGaGe100SPB09ni5+QB8M6ajuAzqtmFWIrZb7d0qi6y1zosJbqLzJbXbR4f0p/OqvJpGjrL02idY/twFBvnlJqTLWdfO+G6PVbj8RntoYWWRnmeKEHUbSoXoHz7fIXfarAvuowRZOtWsOl+1XhD591wWpkVCnWC8skQC77O+CpzQbf8x559gvmaYOUDTYROjxwmPZ6EyOubPPxRK3YPfoBwqtP/1xpBMLwxF2vMihsuEV7rMhtBH0l3lo6/F4G0Eryic6hQYT/Dx7r,iv:JKWWrb4zU7NeK4dIKgA9+n0Lps+/11NMJPQb5VFbreg=,tag:JpskMpIC5SiN88tYnPJUDw==,type:str]
    identity.pub: ENC[AES256_GCM,data:+vbmqGahuxXlH2oUdOUAkPRvQysfHKZMpN4crTiT4EzTlXx34uEGxqkRJzqApAc3JPyXEVk+wZSkRXspcjLu+XuDAFIomVDRvNAi2habPR87MMevBfvuXx+5HN7Pg24jHjyhxruyZHQnfR0VJLqesTjEWeH8+LGsu3x6vqZh5J8wikqEVTTZSw84bw5jk6Ph7vGk1qN8pu+M3788B7NykPvngb62KaGdZZ9VbfVGUd67pza9g8Hp+iQPPrNwrHTRIY22opGkvpXhqb3x2Q==,iv:u5Gj/VuQrOeCWyNup4MnikQkZHuiUKeheSj8PIqhk+o=,tag:45kt3bmBYlzJzYIc/oqvOw==,type:str]
    known_hosts: ENC[AES256_GCM,data:jL8xRSOw+Rg4f+RaP+bqI0qsJvNeV+BOoImeZtPYPwxh0Bk58z2tR9Oj8MkCamQapdcj/U50WCAiGqu59ooBcnSPQkr6b/uciDe+KB/SpYMeW55bTRoWpHHeGmT+f/UZwOkWamnnEKYIF0nNS4bSAnh5y6dERctQvABRZ6z74M/IWglSMyoQKlHKVLgWQkgoHQesipvOUKtuq2C2ZRAh2FHafZlE2CkMingg,iv:4l0XI940ywFz2qFk4cidSElI2egnpMG0M1OIyctGRTw=,tag:nvDa082wvBF3l78CdWQe5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK056dmw5TXF1SE5kOHJG
            YzBZSTdvbSs1TTVPaENmQTdjZ29hOWZkSDNvCm10ejI3TXd2MEpoUU80SldDQkVT
            dkdtTDcyRHdUQlc0eXRvOGcrZEYxZGcKLS0tIDBlSVVjS0t0WEdnTzdIa3lmWkJ3
            ejlYTms0elJOWUh5Qmtmb3BZTmMwQVEKi0ueJMnKCdvo/ivEsHxJxBtITKtTnEDs
            3g1DVmOCMqMkJNTaAL8YDOSWlT1741TwRbsYVhpyMIoGxFdNX5jAqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T22:28:54Z"
    mac: ENC[AES256_GCM,data:OoK/eg/7hTmTyDUCoq1ZvUtmHuIciduC87ddjfIGMutedpIvSiuep73eI0d2VknkezbT0TDR/LgdVXT/VBRrD/1et6k0C3n09O6GU/TdLNk3rz/nvGZN0JNq4L0bLX9SpQurejDq4dvHXgMfPghewZLDZVZ/xCmisWhz0+0XszM=,iv:IWwMzHbIGgoSXop2pGab1fEE5V/RLtmrPtqAjj1R5GQ=,tag:hg0CN/2AlSjgYWVRxJzX2Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
