apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NoU3bfIHl3NnEbleUhEOYk7qJCoKP7c5lrVVT9xsaXlx+0wnTn04maDwwaxdaVttf4YvFw4oOEKj/rjDXP3sFMr5c0J7/pJ20R25EOXPmcI/aZM5UDTkOURIGbCe7aiq+GE7HLHtCBiAyhW9AODGfr/Sn9hUVCXFQoSZpDMHF3nlc5lQr+TnR8X4qTmVZIEjCbYPPTDg5OqGD7/LbbMPbMG6tZGQIXxAcQz+KuVCT2yV4DeeP4cJHWVr6MZShl4Q4eZO7DhEwx65AeUqQUeqapOUSdpoKzdjUQIp/FeqEamBTdy5lNyC3a5D7qVgt8K8gLeEEtStMoy/gWnm6D0nDQ8wN6DVmzzQkTcDq14EGZpcHf1O5ETHeaWqkz6+e3Rq,iv:Bo0AITMD42Ztv0aE13vrAL0KbEl+Cfr8qgZf0yPN/i8=,tag:qo67SYGTyzHjLgCgCWhivg==,type:str]
    identity.pub: ENC[AES256_GCM,data:JF5hwbc0zKCmThaVRakHIisqU3C43a9NtseMqWHvVvrzoaw52Hu99LbxMLd+38uvh6V9G/WeROLRSKW+N0ciGNVsxxhtABIEylQhgRfuW6EkIq0T6U8P+CChWjkl+hiYo4GqH3dy0HgVjQ4rPNcMN+k60ytykbbW47FZBBGxnuQQFCfxr7w+N6h9zb/bBTi6eBdQ4iQ1NRQHxS/SG1jkDh/8kyfK9ni2htch9XqBc7VQZFKJM6frXf9XbvZybcpbsIcLQXgsEOdimXQz9w==,iv:uJaDGqCu7nRez0bqBZN2Ntc0nOKP7c+VpmQ7QSk63Hw=,tag:K9Rp/EInmXhqRP09v9YH+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:PuGXtF8Rsh12g+K06cl1j8K60GxLVw1lws9F18IpF6DA9B1F06Gx0R1W1x6sdWn4uO6zPO25nJVwyJH2a2BCmTJEEuFOHp6CduZlqZJKBVgXKb7mM+/lo3zoikPlcSjK5c78j7c1Bs6rm+bW4FW1GviK/dYXOJiUtOo9sRH4Ml2TjJTG8uSLTNpNYBtAro8WC/rZ5Okn9OLwK4UTc7SlJI2CzOttsqF0elgT,iv:Wrob3t3kCVLu4AIbq9BLBoewJ3hH2R3o6m6FU4/fayU=,tag:/axdirGLk/cJivVTSu8F5Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YURXaXo0aFY2QitVUjJH
            ditEK29hSkcxSUpIV3dsWHpaYWVGSVZZeVVzCi82K1ZsWG1iVWZIdHVnajUvOWpZ
            ZEtyY2M1SDBxNUpxeXQwYlhrc2NTa3MKLS0tIGMrVUd0Y2lhdFU5RUYveE5OMVVl
            WlcybHpXS3JGK2FNS3ZlcERnZU9uMDQKeENsqwVcuLwf4zyZg2/fAt5kF0BSpA69
            BbLee2lq5AcIRXKRETfjSnsx8C+Oqmme1cKK3svlADAcTa0HOiVRmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T21:45:11Z"
    mac: ENC[AES256_GCM,data:G7RmDq8VcOw0IYbfKLNYgyksMHoDkGOBXI53TF1Oed4ewmExYdlGZV1s1m0hbo5A0Hh/6nVT3de7sdfHCqZCaaMLwUEuU5TxaPcH0hfx/4lx3Mh6pRH1sgSgmVeZy4AS7O9IiPLd2hl4QQxMWKkOrC/oyiYJFZeea1H4jDvBS/0=,iv:2u5o1Q8e9b+hJ8a5zzsToL65o42yxGw2PoCXAbMbJck=,tag:TA+bKfF3INSOezJprqRPUQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
