apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aROZ4S3S1WGYxc2YBD/SEu5woigAZ9MuOZ+epiPwK0lHhebjNAFI8CURk0hP4+CrtUvlNbqtwvKheQK4ePIdSAHtbBW/sKElsyqZyBdHBNgYb1Yu6v20nslsJo/TV1S1OwZRFO2gtujswhKtxO2DnpRuLJYWlxEmQevv78/RJtGx76RNBBCOqS0KWzoPx2faC9rRVeV8oxKKL1o9SrGt1Bdse39fkQ0SPAoM9Dar40HuM3qBDPI+zWmNAR8dwL11180I4trrj8R8eUuYROfSYJzBX/VHY90IWnc8vlmYc7/TmQXOAVq/UEKk/elnNCqGYncEQN1qs5zBJ0KY9hqgwAO7OZJGDpGUGwUQ86LaZpvalc9CWJWhN2UhjEGbkHE7,iv:qnfAxwNqJKSw4SRNnGYQJbOmChMVa1M2zbtQEL8fIHo=,tag:Mde0jEB+mcmfIuueN9OZyg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Gg5JB8VjdkUg8lAkndI//mOU4GI7sLv3pWMIPsxZ5m1OkYVbNUC1OjTHvu79wKp1p5Xu7uxY94nZ8/b71wrBFbftj95lz1egVCsyeMWx2zALbEO9ZgjR2C4Zsf71pVjMJyW5Bvc9ZYh44tdsi73wE4RO3NQFX4FnJPLMiutBeA+vwcT5UaZ7Vwb/wqoAXR3FAfjON7T8Olh3u/YlBQ+wM8H3qlJ8vMxtaA/Tu4tQIvEBEcFj01lcB58SyjBVSOZtlaSkPZu+jFzx5U3Xhw==,iv:x/qdp9u5/yo72hxSLgdegLM5O2D4yF/OFosKREYrwjE=,tag:Gro7H4AQejXVb77UQ772Zg==,type:str]
    known_hosts: ENC[AES256_GCM,data:A0bTuYvqlr6bW8Q9vlRKKr+FrDLqD/1jd6dvyEvT2yp/OmCVjt3mhNUhU5u0zUEtVdaiNYGGSSmI71qWIP5h355YxuCgF1TDKv+SY9gpwSRSneo6IgeN+cuucRerQwnAVBGGUSBU4cxTCV435YAbRqvFEU8UUQ+F0Bu9YXVboMrXRtI3Rbc0ZVcAambpuCgtU7HKCIJkG5IDrEHJRcdo3YxCfRKWiJVWzqKs,iv:OXI+2ZR0SYVj0+2kdEBlReuCuSoOKVyZirHxaOj+8QY=,tag:1QGZqA03MzMSIX82nsYafQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MlN3NExKM05IUUZYbXF0
            RzRTc2l2MHczYVF4Y2J2NjN6ZkFPeHp0a0VjCksyV2dvYjdVbDJaeCtkNWtsS1o4
            dWU5T2tWdnN4T0VySmdLVmtNdFN2b00KLS0tIHlJVDFpTklmRnRJSmdRQzRMTXhi
            cm9GRy8rbGQxOFJIbmN5b1hjOWxtTncKErt54EmQeDDRRTnWIXJddL7iJgtoxpB8
            /mvJstdFOwPrgR12WHucrrBwH6BG14PZ7/ad5LNQ5czaSWcC2sQkfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:11:00Z"
    mac: ENC[AES256_GCM,data:utyDBuFXJ6RxQG6rvKSkktp76/k3++3qkzZzhqdYSh28wyOTTXdXXVBKTUsosXMDET6C6+QEjp3MQvqK7Q4Ufc7mQ4WTaRlirqqsBvRx671HHaLJLBZ/LengXELEPlaMKKDzRjQOoeneCLlKvnIO7B95txVyhVeEvg5G6I3RkH8=,iv:6vk5mF55jPyVUxpehGrubFYdZoZ3B+z6zkVeqvL6IO8=,tag:d5chLjkIkAP0mB44R0uCiA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
