apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Vy09okG+rABcEC1491C8h1nJ0099Hmkefflcmpiow8LzUGCZ7Y9YNaK9UmgdrBJkvFvSXrH4gbWugDI3rB74OnRURuzklrSBUxTQVi2C5Fd8JWka3KbrlFdLOWlk+rqSCuQaeCAX3i/wsFEU9m23NpOrlKqIbvtSOIrU55aqQoyxC2uWVX20KfNr6rbu5nREEdRm1vaKNZv4mKTROlB9FOs6dtE1mk5AyCfUAnhD9zHNfkO3TUbtNp170+qRSikfH8OH7IhUez+kOSm/oseYCfyGLl22fgYXIhN+mwqU4NG99WD3Cto/lK+BYedfL+5IGZAArNtI3uX+xcII5d6E75qykrGrVCwwnB5e/z4BYCpfuHe+04gLJ4DSeI2hMajG,iv:UImsqxWaheejOmJmcBRDDNaU5aZpg1KCLVkZZoo9sJo=,tag:xf+dIaVrrGOa9lm5zSclQw==,type:str]
    identity.pub: ENC[AES256_GCM,data:hDZ23EYC+K4UuhTFRtj0e44WReKH/7sCNhPzRJs/vtz4vfs3dbRF+VhllS2aj1g2CTkQhkcfxXSR5VpOoaT0qAMbLzqAKUZ3Lsj3wI2BWRvTZ7K9847JI0pP685ftT0PAOsfw5pPDF0l5ffphlw7V0rLkQJOevz7CCqImiF9az3CxZerFfO9Hv5nN7PSLpdjffsR/PQrkrJ5j2rrs2IH6h0qX1RsO044sumJ239RJykzyw9DSlSPCStDZvrXS4ZuHaipfvaOoPA3Gm5yVg==,iv:Nvi99bu5Jw7iAJZGl7H6RP+fRWksWbowiNoeGhP/bwA=,tag:H++kVOnlDuIxrjEUrHYKsA==,type:str]
    known_hosts: ENC[AES256_GCM,data:o020FLvbuyue4vMLVg4sZi1iW/sPGaU838mhrMFX2bMqgkqMKWDasHSnkxuoXcTGZu6SBZWnBGPqMxSzH6ImheMc9dvmM+xJy5o6STYB0RDSsf0YStVBqWYrRzpdpcnCHbrhenTzoi1zhe8nKhpDQnPbzALs4j/VS6qdqYcrXuoWDCLUD0MuTSadK4jqZSxKIQpBAi9o8/eOAZke/xnP+w9du9sRROTUYcke,iv:BUqd3no69XM4th0VKPoj7DozX/jiIcSlanmZx/ubNzc=,tag:o7Y1F/eMgDXkifQsQVADxw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN3VVZ2wxSlJmbG9JbzNq
            SktmS2U0SDBkVzNoc1V1dTlnQTdZcTNVY2ljCnl1dWg3Z3VUU0U3YTg4WFlJRjJo
            dUZuU2NYQlNYczF5T09qdURaVHRvZXcKLS0tIHh6cjZUaXZlRmpOVGpCWmYybFp5
            U2NvaUk5a1pMcGFuK3hGUmlHVkw4M2cKLqlpR2Scc8B7Pe1zBFXheQRFjrB8cGvc
            7R9SqPGgmVKzkx6NwdbKawMAIvfALUpXcZUeSVkNNvN9xaE3IhdCYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T19:55:38Z"
    mac: ENC[AES256_GCM,data:IomUYFMWlcWLEeEk4NDi7bNgoEoIU9IxSYDFLEd4S8Zggjn59QrmnOkG1esfrBoseoY35DurgfFsXAL0LJt1uhy5Ot+Z9OLDsYg19yxwblVLEDldESE7T+TrsW7hFYZVX3RDyoEOytN4hPirxtmTE1t7lE1GYmdcz6X7QXADWF8=,iv:UBAkyifK6yshcUjufHM38ND/EkZYOdsCu6BJ1/pAPPw=,tag:qwGkYZH0l7lrCdopzqDzwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
