apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mMnB3EPz6kOTY9TWCNyQmfudVaENC+2FVe3ALYLwCiiilAvzfXs+yeemw0gLd9wP6GrOOMIzQeK162wnvUdc3OAXMDmKQ6ReLW/Fen5Ee1tqfDfdEZPc2mXT7Y+e4LSkGeEvuNFWn6Dc8l/htDXluRd8327nxN7XWvv/7sW+klYCQTemLbBfKJpxBe7NVusYapRaTFySApG5GyLmQIcRnvEguh+Xk657DTLlQwRr45uitlHZQHcSWgG3Iob4frKPR4e4AyT2nhhLKOgly59wKQJBukgHooqwpC669nO+dItMXTZlrl0iNmFSiumuV7RRvDY5+T4VP/bF0CI5foUVkZhU+Hp2pjQLxKGp6BoauWG3u73J6jYFVxW6+xy41p3+,iv:LP/5L/hq6Mak8mid6J/VqkFdlH3Xor7ecVcuj0wongw=,tag:8tWoTXpSV9d8RayaT4DBog==,type:str]
    identity.pub: ENC[AES256_GCM,data:W3WvLgYDiI9btiR7jOtTmhYKeIyOwnqWVwhQ53l61E6akOqZdgENJ/jpIEMVmnYH2XM7x8x8n82cUZDN2bpNHDNDTNG6Gt8q8CfWaqyJ5ap8o6QOdTfuvJ+WWuWozN9pRf8JzjslyUSEmUDMfIz86pmMlBxKE7Woe+Bbd8ATI5oARTegN/aYZ4PiDZpRv0tEGhR32z78AzdMqTmbH/9iNUaDMD2Q9hcKoPqKgnQX4c/aj9jH/twZKlsYcLkb50xokQlE4hXv7LXSqep6cw==,iv:e16Nq6Oy07PklyIq1hyOrW6X6Xi9evskL/AsYF3w7gM=,tag:L3OmbYxRTKCB8c29lzDzTg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ot15PfHkuU04Rlqm+hN9o6e7Zya0ZCUvpTPQIAl+o2r4carhEFsqNsSySnI9aGAGpZV55PdNlhpMMYmr06wN1t1fYqV1ZILKy09jxBx/a2rsaoiZnwdDJUqnGQusvzSpHr2OSAIe72VTpyGeGxBoF8oRK38HQQt4MS3Tw9XbczC4UjorZgGwda+0vHAN1pkGaeXkZww7Agb9NhnPmF38eKFcjj34lok6x5YA,iv:K+6i/WYZxfpgNICuldrinTNlbFosPBKN4W8wvIQ3Ez4=,tag:e3lR9NcY00LKLZyy9PKVQA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c3sr6exe6w6vrc5kcpmcelru8emj5ppkvc9dtmh84jp22pnm5v5qm8cm75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSSs0cUJhNlV4WUU4TWUy
            UlNSeGNJZld4blJtQ0l0c004SmI5UXF0eWxjCjlQcG5YNitUaXdZdFo2cmNyNVo4
            MHo2UGpvM25vNXJkbzM2amErQnQ3eGsKLS0tIEFCU2JyOW9keWU4RElKVFR6Y0NY
            aWxYR0pRMjRmb29jZ2QwNkdZU29oVVUK2vAw34eE0QIgRduWYe9cM+RoUSljuCmA
            99ILe2SiRUSRof9Ah5jmJPL9GjPJX0xner41sHtMaTvHCDrgfVcnxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T17:04:00Z"
    mac: ENC[AES256_GCM,data:bWwHITw7IFuylCxZFVi2bHZVALdHiifaXfUKS0UIw2HdZiFbXU4fRg/IMXaO/bdRq13bEINpjDNPmMwnWQceAcnAjyBxA199JvV+qYX8ZZdysFEk1NZ5wDLpA6vRiEeQ+Ws45vvqv9WNE1mxI4agldz+Iv+NgcI6v4ZxGdt04Mk=,iv:Icek9qTxodR5AdCLGfaZ2COh5mNpsrCzLUEHYy8NQTI=,tag:u8Jvu8Ve0042WrvcAW6UWQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
