apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Svt1Ja+ZDbGSRQ/uqB7ktjoaCUGeZlXYeyIFCFfI7cJUBCezFS/JI5F9sW2etVlXoYf7CH/5Yh7FPAkhbespyVR5SGy2ITA9X9wpNmjaSBxjUJwk1AxZx1mId/Hw965YIAxwpMzoODVvCpvG7ufEgh2R7XmLhAZBg3wXFU2SKfAxfmHptcrB8fgVYROHmGe0jchbGg9lJFMNK4h9WTDDN6FhoRD0u7LqHkeTHkAwCQysF+YmO02ywCZxmbK6V7kFCckgL8IlQtMv/ia2/V183ojKGfQJpFPosQqza6naWe5rrMMrz/xVoJyfNpMyRAsPQEnMzQfLiJBE9pFOLFOpEz+xpbNqxe03A7AtZgWagPpKtSlvCFbm1xH7dhlMegQp,iv:ORf+5C3Nyi61VvEp0yZFImZyEwlU8Bi97w2Geeb5Cls=,tag:cOYDPD0EPIDMKSRnqFFQfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:if80lT/K8gbXvJWJxxZbnW6zt/UgwNvs7jKDnSBZCyEV9aNakwVHqNFvJIDrfvoxV+4CgmVhc6X13Ee+jIBWTTZdusG14/AU8J3lHBf4xcjo157Z75zB61gkFYQAkma3SiKB/O9AUVF/PFKj6cvothu6CdnXKpmPl5t7mwy7wvutkx0oBokQ5d14fpsgHt1S5ZXGZV0nwyrAsARtV68D9+Fu3e8Lmb7KaMLKZ3SvRTW7Lxzb316wC2AOOKOXKLQSkeNWOZ1og/chcoHtcw==,iv:nk3gkt5L842hyWyTGYm5X7vgBhIalzrwSqrmBFxRquI=,tag:F7tWU5PQpFWimsllPlxe2w==,type:str]
    known_hosts: ENC[AES256_GCM,data:TR0eDSE2/jrZd3RMgQrPSh7othDoYn21ClFtIogLhQ3GKnD+9C5lFnSXgdMvSOFVoMLn5OhyytFGNEIxia+mhC/JdKreXC6TCt9/c1+jpoHK34o9GmaXdKsSJ50SPMAAWJ4qhPtS0tQrT/Or+LgVV4a34YuYe5zCMXDDw1lz19ApjXE9n3zzVbHu214TcneV+zGgBQ3ZM/ktxCjUb0/U5j7YzLfJxJ0NuSmD,iv:jMXmUB86+Tr6CTPPFzvkKq5uUC6KkaRQQTh+1zmz1ns=,tag:bU8JEI7O20/A6sSuM85MLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR3g3RUFBM3cya0ZJOXU4
            eE5XbXhhbTZCckdMSVByMjE3RDlFU2UvazBzCjJhalBad0FLazczakxYbm1JVExN
            TUFCeHd2RVRuM2M1UGFXakxPYTBSdlUKLS0tIDFYTC9CUnBtd2FYc2s0T0xZWmc3
            N3M1QzNLMUdtUG1nK255eHdwek5OSkUK074L2Muh32lgnSVTrBJa6DBkM7kGdhya
            MeYp50T62/NY6B55hkXAGZJKniOv3vrrwxQjKsqMzRmVnmVfm9G46g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T20:10:59Z"
    mac: ENC[AES256_GCM,data:pUUci29dmnspeZ6Digslzf1Uz9+63q7CjjecpZp1DJVa3G3+SV5LJqIhh8lQpYr8Z2YG2MyOIGMn9/xHrmPP5jktzokyspvWtV3lbsF6vGrtxa5C9xBflciB1CT0wvMNsFo3OJz3YXF2OCAYx4HklxLZ29rcxiFcYGnGI9j6qSM=,iv:FvROl7IIuka2HnWgetxh55A6u4wkYqEJF2oAfKwy5vs=,tag:CxRhWeXRfsJUaCE5c+7s0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
