apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gGQFYPTWsq0OiKIkuTFDXeH0O3FF5CpM2Fx1GTfeAl7mpMb5DMCeioJQLh6IENgrdsnhSlkA3+QqlnbX4hu7F97grvdoEn5zvwCQfl20PdPBFq+koCloNFmN2sQ2P6jUFm0IruaKawD0jpV1KMdAg4tQrLf9mesVPod6Pebute8I+XY8A9UDIgLg8m5ZLic0pwiYAo7CIew43CkldOHS1rORJsmY3LKajdc9bQk/jAa4CGiP9Km1JEuPhfV982NqP5bMd7gx+J9yMZwll6SplF48lu3JNPW/J29SgFlpkhEZBvMm2e9GfEYYMmind1gmhraQs+Acokowxu6hOvp/0W+SmC/8feHgqDjn8l1RsfToxBD3nQ+4WTONmbKRkpu3,iv:mdC2r7D0dhiBvIsrKPXHHPpgUNH54XPlvMWc+ZtBvlE=,tag:IiA6J3lNv4QEAXrd4M7UEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Yx6teCsePba2FN1+mNeCdaUqU91kEAvNe2dLHIa2fB2VIfNEds3h+W4h7cG6gSQ9kieFlmpE77EbUi1ml4QV4P9u8ieZzYuYXCT+/V6dhbGrishBV1yPiuJOiCe2v0Q94RkaLIp4iPyKC4Tkn9lSzkyk6dokYGV9M1Yjx+q7RPIdNVrI6lxJrjt//QFrW6pvneaF9dBDMWAnHYMzicSMTu8wexJzXsTvQOfogK+0RY7MqEjx/5zF3xA+adpC9KFETeum6cMXAgmkU+YqDw==,iv:EbLMxuFBJ9xIAFCqPgDUDFdTy1VBvgDQxYJnZ8rORl4=,tag:v0RwRFvq6Kh1rHfx6tTw9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:APCRpCbyjc3KIFTE9rmGeD6fmMxfhXOT9nFK8paN7J8zOG99ZxA4x8K+2Yh8gfKzYkqVDN3hipfT2vTB+BYJwqiF9W9zd5lExHwLmEbX9cSO2hQuo7X6YpdEBMj/96/AfKZwNX1uvfG/SOFUXvZzqCkxOJacFjeKtWAU0gtwDTYiWhmcIeKYEQDgCMgmdAFRSwT/Zcv4Iuzr1BoAd2Kb+JkX8S25ODSVGMoe,iv:o8e4kUAtJJsJavYt5J6BzMf+46q/RTddej331wVmUKY=,tag:KOlNNbH8P1gK8nz1sV+8zw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWWRjeXM5Z3ZjeHVvTkxw
            N1hPR0lqN2NyTld3aHRGVXBpWkwrTU4wRkJjClJrQ21yblBvV1o1NFQwYjZKTmF4
            VWF3OEFXMXJvd00vQmdIMk1XRit0YVkKLS0tIG5oSG1IVmdMQzJhSnZiaS9SMnlp
            VWNIUHNWRXZvbitIQmtjazdYQXF6cUUKHoLd1Eq3brQYnHXzk9U/UaPGJZ17X0By
            AR3bH6CSvCqbwh6n29ji/9347R/4lJ9o8JVkXDYVEtFiISN88VdzhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T18:41:17Z"
    mac: ENC[AES256_GCM,data:FmKBtNIpkZa3JzRL6u5sQEqQk2rcc0JMH8GNTZ1NKamR2b+tdo+HLo0Y7cCCpLRSjzJel86h+WY8U4Kxr8ETTbSZNH+Ka+iLv/m9cwidri27DrVbK29vaJ83g9Gys7UXdYXjywDZ2Uscw7IUYtxGWljMRm5Cai6BW5wxlZyhW/w=,iv:AHaqs82WUgb+PV4VEu5Md00Ap/RGTSdhyd+ihtfiWKc=,tag:vWO22Te/ql/VyNGs9JLt2g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
