apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VCTUqPWQKe+oVISIDgtsLK9qK/lt2XV0HAWT0BKURS8L9qgMHtr8DC4CBrtVMaixNwsY3c3nP/wkpL5huToiGuxgb3ALlU6n4Wr1s2SH6vUlHcdv88o1XVwU85IicCRS+oTP31JCFM085kyxoYaUFD5CxCM4smer4IU92pF0piucv5yr9tKu06GQKUhmMd7zxN4oCtqmdRG3XtPxGRrF0hpJPEsJafaGrUCYn5fp/4mEl0ba5igQfyS4OqShlay5I+Hi63jxYxecMNwUC2bkDRRxSZSiMJw8erJEShSCCeWkYQxlqvLPbXlN1QX77laOKXTRiya7xG0ZvrgrzSdduiR4esFSxtIvXGO5fJ4INLtbBhwdgn80HkqWVoJAbTwo,iv:nXfI0Z8FihgzmUGb3o2DvJ6oVo0Gq5i+B/mszvLI2dg=,tag:4hrrBrB/OTKUKivQy+teUA==,type:str]
    identity.pub: ENC[AES256_GCM,data:FnHSr7WF7iUQ9RIh3PO5kkn4QZeb0+DfeITL5z8bde0TsPZTjNerKxUacAvZqWfoFKXfIzTNt9ybZ5kYUCfEA81GGLsdC/metEEBOBoTtOH399RlvwCVk3uZuWjWrOjPlNPdW5wVwvVAb9oXSPOgraihyu1I75134Mcf9iWCe8lTUUrn9+8jb/e6e+/jEVkIa6gKnAS5Rgme6gsM6CmMh5rpDTnqoe89IXOyR1B+ePwLINxXg8EqZloV3/ZMfR/yvq7bt5Q+jo0AQImHDw==,iv:jWvYphUIBoFf7rDWLYSBJayn96ljr56mdr1p4Uk/T0o=,tag:k2XGdCyWLXA6sH5f6gZgWw==,type:str]
    known_hosts: ENC[AES256_GCM,data:R50i92rEvyg2rIlfdoVg2hBK4KKmMhD4H+qOHIruNgubPFWUVRfvtM9ytSNzk7QsOECGnOQTOy4J3PeWUq3cgGVRMexVvP8Dg8SF4kfyYYsIiaKdBDaTwf0SE+GIDT6Nm5kOqOENzTf9sFcbn/NZdDlymFnJ3TxZzt1aOUYq8A+yBLRRihEPbxIr73GVotECGBWpLvsfRXTT+2+AVL5zZI9XXlTpdqDdHnVv,iv:uZU7R0L+ERuseWFbPeCagHjKAsB/cjHAGIJrKcW+bk4=,tag:eB3r7XH11ItC074Ad40s4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MWt3TjRQOVByQ2t3VVNQ
            b1l3b1RVYWY0ZVZrdXpGRVJIeDhibytXR0dnCmVJWDZzUlp6VWRkQWVQbVhGYmd0
            aHVldTk2ZzdpbkRGM1lDeHRCRU5GMHMKLS0tIFZwaVZTVG8xVEV6TWp0ZUk2Z0Q4
            V244ZStrVFNhQVFmUVZRVDFMdGxCbnMKsX/ra6aF8vL217qEzina8pabCxOLOxOA
            RkxxI8xuu1T8KQTf/kTmKZvDftP+m4oX7ojhp+/0SsskZIcs3GTzkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T19:55:53Z"
    mac: ENC[AES256_GCM,data:+e17oh5kZBfWWLEVWWpTiIv9pPAZ85yCOlCZN6+Hpc83hDCuuV9r3HTdPggAXXvn+x4GAYrC2rCZF4zZEchS+hogz/qFgfW2SUaWvxicOyRHt0so5rdyLFBZrUjmNQld3M+RA0bp5Zi+zyLhfuPbhCRCQXCwd/QWZKK4y1SE5H8=,iv:GVZwziiCYlw22vva7Ld8AT2zS6NnqEcYaqOYOBWdvbM=,tag:1STb+E0jaaou7aKkbSULCQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
