apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8ZENS09N2Psv2U2jUdtHOwApsH32WEYJrtRdnNA5/dwy1cyl+ouit/62BV6wiqmo+B2D83UkUAnngba5DEvnjuxXZFMw2rLN+JCIWdpBv6AOcsG6GgWZRWdmXWUeyphP3SXhTFzd1aoRbqsog+jgzFj+kpSmdXqSkypzXTa+uPi6sVc/x1csp5pScwAfUVlAeLRZIioY2jRE+Nz/Zve6/Y71pPWjxfcK4UoGzxHukYq0vnjZkhtiE4xSVzuYUKXabcgdydKlntQAXEyzs2jqGqWyTyG62Q4RHMs7MaZyastuNrTshSrugBAnEHhrYpS9YNCO7bFszZfFCVZiPyxDMcHANikbKccuIy59ROCdwVrZIjx1dpZv3AVN5ZlLWH0S,iv:wyIg7ieVRr1NCDezJx+uJMeDZgThADdo04aMAQFErdE=,tag:EvgxbRT7JAmM6B1+XzzFdQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:hG4nd9Lb1NG8vauq+re+3EbMNpDpRLDl4igLUPIpCopriX7icAzWELJLl/Qaqnf4/CpcCUs9Q487EX0EP+/x3Q9P6mPWm9hQysBkZ3KMp/0DhfBZgiOlkFpQlK5YB0yMiejPVyklmrAwu3HW1uNRYT1M1g5VQCZxF+8Vewspq3CbyJqQ/4xJ4f7L2vrj3grhVLZ00bVWe62ix6qiNU2GnUDZB5sHJYTD2kPGqQpFV3NAbpfIvpMZ6TyxJVOe6CV+i3t+dX9zgkQg4cwUyw==,iv:ShwrpLk2X1tnH33q8ZR1mUMncMPztOqNIwkjiMFkFtI=,tag:DffskcCUw1vIJ8Y04reJoQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+OoOnPnpVffIF0hgultuR9dvz20tZqrQdQkgRGYG6vyZBeXSw9fMmRFUvbgFE8ufa3MIqwbKxDsnW8s7yNiNATqiukVjc/ydZbXVMkSwbj0BAR6ZEYPIdIyuaY+TYd0AxZCrezio9xJvEotDKedXoiUjuE4LsazYVa2Z5P+52YhJ5oOy0HsehlUpFcP31llXkcVLgUNZcHBcgmoM+DODPm0L4ZZDK5d0leiT,iv:UB00ZENaD6WyHHQ7hvLeVC2JzdoV+wp5J26+2dV7jGE=,tag:Qd5mcDg9MWbzhqg1vJzoxg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMlVnVG1qc1M4TGtsbFAr
            ZERJQXNQRXJEQndBZldHWVdLMlNiUUk4cjJVClJQZEYwSmMvLzhGSW5ZaWxPYjVB
            M1lxVUg3TWo1NE9NSllqeElCSDNOK1kKLS0tIFZzckdLNGcvZitRVEdLak9TREJ0
            U1dySWQzY0RjQnl3d2tHNUczdGxPUEUKEJCW/KWg9ngK8KoafgF/yPijlyrnmm5b
            bOfbuVFwQMRA3abwq9YetlXydtMMwbwiXjkFcJCpeiXPTDTUfM9aBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T21:48:24Z"
    mac: ENC[AES256_GCM,data:VPU4wsqC0tpx9nmm2+WZuReA/lNChydJI8skBXZQhLRdWLCyhBY8Ls+YQ732RU/jsIjfZ9scR1Q3ek6BY7F873q1TfhN4X29q5JAOIToxT1WJ+wGep8rCIkYUUElESYEP0DnwG7ApeQtn1R+ojDt5UkpPBsRIwMXrgPWsLpOn4s=,iv:/JmjwB9HCJ7d7WcQzM/jPAXxOWpV85GJVFZSit4sp04=,tag:FDuDn0ueaHJt9PwXtaIG6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
