apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Vaw6jzPdsLRK7oTGCU5Du40qNKYyg+yoXdMbAp7kOCODh98vIhU8BxKw4Dv341eowtaTYUzcsXAYFSRhXT62AW3igcUx0wu8vJDexgIPAeQZAxopFtwMSd6vl7oBnPLdqhhmD4CSDUFAe2WUIJoONIgp4qr9gSuxz6YNifp59qQVdVfb38xfD9fw3hePYa/Qo6buDSE2+9mSi663+pD7EbEvQhrWawvI3l6kv3WjVHcZNGNLLamEWFn/eMgK+Z3keasLYTgxxUtNejRkOJ+OwFSV8DJj5C7Vk6MuylMQRQizuh7IYY/GeByjEOtOf94W9rx94Lo73io1zFpi2GOfRlVdZ3jz2Ah3IfC9q5ei9lGfF51wDOsKGBUudgR6pJJ2,iv:kySGMXlify1zmSisZZi8K1Bz8UxmqSvfidC3NTxjOJA=,tag:LirTuitMGl7gzZaVm+1fSw==,type:str]
    identity.pub: ENC[AES256_GCM,data:LCXGidBvSBPd1HLPXnawtCyy25YHHcrDdpkeYgIPGzEcU/ofEGqx2dkhsYwRqg060abT3aOmOv/e22p/GgJQ6LkHPRF5D8Gq358CkHBtho6ffsidQV6WYqwsVc4McnjrGuOKcYpurOO2v94/6Fn2qx5mJlzJhgWu0qVI/qhNg5J5StQXOUGupcOKyo7WMhQx7Qo07JfTAtjtMS0x/twkM+7Xev0Zd3qw1aYra4NBsb8T0hv7/vmsmjYuFiQD4UHr7h/zLRjl69CWsLc3Xg==,iv:Qd26HwqwRHEVi+s1QzZYi+4CYwRN66t+cWyzFfDnVgg=,tag:8dPHp+ezXnwoL/82Pt9v8A==,type:str]
    known_hosts: ENC[AES256_GCM,data:RTNXczPZan/IfaRXiub8FR9A9zLQ3qpI+5isWXboCSSfM96JC15i/gt5d5JU+AFIIPpNfFC0WacNO1MycrGNIqWgjO1gsLaRdouSgHRpPiI01ztH6O51OZPjM8b27yNg9qzxUSIkf8hg3v5FsD6NV1CT58YFCe7zluqHhPCRfXZOP/lMdH3lYJWseC6s1badlPyQSn7R2LH0PYzhhGn2M3cXg6aZwtljgMfJ,iv:2urx0yboPnUmIF4u3LGBq/Iuvxp5StnlZS3l2VrWam4=,tag:/Y2h9sHVsXi8sY6Oj1YLBw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZDNoR0ZqUngwRDRNa1Qz
            NjRWQUUrUHNtZTN4R2hMVnE1RGpRZEpTLzJzCjdwRHdxUGpRWnFxMUF5dHEySXZp
            OFBRSUkzc2cvZXduOGsyYVh1UEZ3RGMKLS0tIEc0NnRTRXh1WHY4S0N2V1M3dE4x
            MVVxL0ZZenlWMHErV1Z2bnMwSnl4S1UKDDNQ9KxZ4ECKfPnijV/4O5kpqkSDLMaf
            CydpYY0XFq5pEsAoUkFxGilGGn50xqicxgd+LY2ODRwXTg/p0ZyWeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T20:39:08Z"
    mac: ENC[AES256_GCM,data:jquSKJihMcnPSSwnqZAanGjydjvZKjjV7X71fXjWmWrD3oRBU6crRiwlJ8n8KiRQ3woJKIQc4OLveoZyDzRCqjHN8W8YW7jce1E50G0JtX13Q4kgh2RWD3sYhfogjj+H/tQVz0b9SqYJFSOZjFRq0AlxznFTPX1oik3h+HcWwLA=,iv:WJam2TgDHfxhjwPfwlGdVo/p6h24DtaZhmvBGhlsb2A=,tag:NGZqbsOonEIFr5V9pt20Yg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
