apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oZTCYyKTsqcuftJ5wApDtphT0Yvr46T9Ib/TbDJxkzB5YLLXcL+08bYdUVJHCMC6uCL8ph82EQ3VK/FvR+ie1o4xIxNgT5RYOVCstNOfxt5TlbhsgZC5GDWDkWxAqiQ4Q8trHQO7JmFron5MOWM5YYogD03Uxp0/vTfhlHVk2fyVP0VGS6h68VWQ45UYL1zmeMFyUSmMLblKOELbazwc0q3lns4FVw/Q4xaBOqYXxv5LlETQn3o139DLwqBEBX2oCEardYosYCt8aQfqFrKXAZJCb/VKgDUIchxO+Ax8LUr1pYZO9/R3M33K/wwdlI38CannaZxcBpOmzJB+L236HbDxA4RXbMBZ2CiGse/GLUnAbYeYa3VCys6YnKgQrsge,iv:gnCtKJ0Y1D6hxtuO//8gMDlN2aEuAdTHrLbp6KegyGQ=,tag:duQdPPDa6dxUEC+PWOOxJQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:VIeFINJarwEeKGTs4l8lzJoh9Z9MvaA9ZoCW+pgRtas/w0B8PJEFnhzHYjgCIF4suzg/x9KBQPstoaZfTaCVAqhR0uoVcBjvGsvwc+VNh90U8WfKIEhAsC1yFZzrZi9jF9iQbyzaGj2GrpF8Eq7f0TLmhHJ00GWKiAXSHLkc9WlURILUxqxrIebp9Uw5CGM+4mK8hEuUS6o+WaucOtBqgUq1U5EH/udQ+G3qSYwNeTB6xcdehCwHTgE6yJorr5ptiH2EA2orfxwWxjmVYQ==,iv:4P4msfI5HA1B629WvmZ5XnHRCzSAXDkGP7JbUJauI5s=,tag:XUQWb2gaU9r2d0+rhcH5uA==,type:str]
    known_hosts: ENC[AES256_GCM,data:GojrqbxXlJ3s/6UC7gMyizlG+UuQ3m8SoCoSzQVWEO2v/40T65Vpa9KlT+sZy7NXLIn4GKghNm0G2b1HsonLmTRxuzx4lf23MP0xw9+3G3Y1uhbrUyb+iBeRotTwe1P1c0A7NknISLB+HIi5oKLnizHObACFzBlup28vVnCFATIj8uFXHQtpiCBYDUYVXDUwtRZGs9LcFgXO8rRPZuscp5jX42tTFoaISgS7,iv:5ZakHtXzl/24dvLK/0CMgKq4xtCPARCk7Xw3ZGLhMlI=,tag:kxaY6/RNq5FI2AduNvWjYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c3sr6exe6w6vrc5kcpmcelru8emj5ppkvc9dtmh84jp22pnm5v5qm8cm75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPd1UxcjcyK0FFVmlIbU90
            ZVQzQlNDT3JZdC9FK08zeFAyRGZ5NXh0TkVjCjF1dU9ic0NXZkFuZGIrOUhWMXBO
            RmsvRTBGcG5XdVBxeWtqZmZYZ25WVkUKLS0tIHk3WEl0eVRmT1p2VnhTNGVJaDN3
            YVlINk5BZzZKVEVsSUlTbkxSUnZxekEKlsq6MneuBUc+BVTCHJ3EeD8nRKGXpBVT
            6d7p5VNvD04IQU9LJIZReloh4i2jg3uCm2GbhxUaP5Un/qJAlD3b8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T17:10:37Z"
    mac: ENC[AES256_GCM,data:m2vtbT+vRgH5wzpEdX74h1OWMwFXNZwe6Tp9BHHDijt3PBA9zLwG0mY6dOUuChKzVOTnLMdPItEzJG53bczLHZzo3hXX16tzqWH4nYoS1rVn/f0qvV2NC2uq3350YuC/yixtWsxC2edZkpBp2kLOC28+YYjGj1nUKhuIbaGKXTc=,iv:mCnkK0HXkjcSpv9m62eqBX5jdHssI6ADMPRPaw1evUg=,tag:AI0PFjDFOIwAzMiL22oydw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
