apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZN2SiiFZc8BJMAJnOcgYjWF44xO4ct/y+4hWHH2D9uReBmet57VCpZEq7Lz4N3C+OhN9csDfbGwI645L2FVEPIZF22VKJSeco8aHpXqLO5KrzRDmTLVVXsJnWLt3NyebQGWVVNl57IOE6qbyOMSxO/RxuobAF3dqmInFvTOSCfUkMvitOAOQ4HzAFIR0CUgtdP1QQKUrMptt6OIHPYaibYwhfgGFDbelzB4OenN11UiKy5YS/XTnE7ZT/suFvVn5iashd6gyCMbP+Bo1UUmB91cx1+VzczTMFZvA0tCeq+gm4CPdUpeRfuMFpWadnRxBQfepDPCnISqCHBVLtpWMnGU6yPkOFfZkWAEuzwyY84vO0Fc2dNZN6jJyqcGtaomt,iv:juxnyi+XLtgFAsFdtbxq6FA4NE1lmV/pBycNNKeK6NE=,tag:86avvdRjb1Pkyyjtz35zrA==,type:str]
    identity.pub: ENC[AES256_GCM,data:C1gt34dJERjYwNyezoDevkwmyUDeQ3+kJsfPS/uI/GrKwg+fTY1E/PdAOZNIJ9xlLfZedTVQnqh4G/Nt+FwLbwUrLgc/RSOtEXiGJyKnsIdJpi1uiUPoK78F+v150pHj0aE1OX+T7oIggbUjd3tEuPQneLZWOCKo+IDwo63YvgZ6ybOfN0ZnVxYIxSHKOo3xcPl1G5IswH2KBy2POqXGJa5eGdqeSsMHEDq1FMwEZ9bWXGu/Sg7d4RpydsFAUwxBTWR/k7PciOfNyHTY4g==,iv:O0uw1Yc33MYQaHCiTORHgm6iyFbt29TXE4ZOpid7fBs=,tag:dqBWxF3qk4uDpu4rEodoNg==,type:str]
    known_hosts: ENC[AES256_GCM,data:90udLhxl8SHKlGRqbA+RFoiSg5OSBtBolEt48r5XAFLhvQb1F/pF1/feqJPBXRSdNBir6Eew0cxm+YBfkoqcyiUa9PA5OCqVRw2rGE999QNGUffec/VAhsw9BOsSWi6IyUIhzfvLpLi631uIdMBG8CtSNuc/QtMjjbBL0KRFiqK7wn40F9CyNYfntKsmfXEYszzvGghdXJFQQ22loOBXVt4ygS0j0Uqhjggh,iv:2FAP90MTsMdqlGmo/0IBuVW43yaiBo5YwiZXFTZMgvA=,tag:kT+TnjoGoNOweN9leHHTCQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1qf4nxu6mqqvlarzw42ep4xku632pgv28kt4gm2rrsaza2j70l3uqnhs2na
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWklMeHl2SzVucndsOE5F
            K0tTd05xQ0JqSUJaeHdOY3pWMi9jVDkrMVE4ClppVng1ZWlrZXBVSTFvV1kwWXBR
            cnBmVVhwaVlkK3RXeHA4UFVOVnZaYlUKLS0tIC9sd1Ywb2ZWV1JyelIxRUlMZzJl
            QXVQVmU3TlRFNmNKNlh5S3NXeHZsMEkKBygWQ18ZY2p3kil4zzIJQ65y0nQjYLI3
            4ECwVtPNcuUcZszchX9fwSI4tLQ5a5xX0cV6N15P7Uko1lOlCRMjeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T19:15:34Z"
    mac: ENC[AES256_GCM,data:0qhnbphxD0gyOPvdmyrIir5oQ+b7z4G6NJeOnr0CBodnBgqReEN52/SkYoOXsDcKoQz+VKnn27cBYXy5oa+9EHWlMT/A4cRnYoa6pfmPdAOfHm+YUQHt+YFQq7lS8LO3dSr1GpAqg/LHSQVr31Yxz4w5RNnNYECO1pXaQMLMfRs=,iv:bksJtg/kTo72NhsTpUG8KHxjgAYegRjYYEl4VeMiCZE=,tag:20Z6ItQHp51JJYHz4XTc2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
