apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: omada-controller
    namespace: omada-controller
spec:
    interval: 15m
    chart:
        spec:
            chart: omada-controller
            version: 18.3.6
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: omada-controller
    values:
        TZ: Europe/Berlin
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                annotations:
                    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                integrations:
                    traefik:
                        enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: omada.${DOMAIN_0}
                      paths:
                          - path: /
                            pathType: Prefix
        persistence:
            data:
                volsync:
                    - credentials: aws
                      dest:
                          enabled: true
                      name: omada-controller-data
                      src:
                          enabled: true
                      type: restic
            work:
                volsync:
                    - credentials: aws
                      dest:
                          enabled: true
                      name: omada-controller-working
                      src:
                          enabled: true
                      type: restic
        release_name: omada-controller
        service:
            comm:
                type: LoadBalancer
                integrations:
                    metallb:
                        enabled: true
            main:
                type: LoadBalancer
                integrations:
                    metallb:
                        enabled: true
            omada-tcp:
                type: LoadBalancer
                integrations:
                    metallb:
                        enabled: true
            omada-udp:
                type: LoadBalancer
                integrations:
                    metallb:
                        enabled: true
