apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-pt-wing
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/external-service/external-pt-wing/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

