apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authelia
    namespace: authelia
spec:
    interval: 15m
    chart:
        spec:
            chart: authelia
            version: 29.29.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: authelia
    values:
        TZ: Europe/Berlin
        # All configuration options should be put under this. Supports all upstream options
        authelia:
            session:
                # Be sure to change this to your domain. You can also define multiple domains
                cookies:
                    - domain: ${DOMAIN_0}
                      authelia_url: https://auth.${DOMAIN_0}
            authentication_backend:
                # lldap setup
                # https://github.com/lldap/lldap/blob/main/example_configs/authelia_config.yml
                ldap:
                    implementation: lldap
                    address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
                    base_dn: ${LLDAP_LDAP_BASE_DN}
                    user: uid=authelia,ou=people,${LLDAP_LDAP_BASE_DN}
                    # user with lldap_password_manager group
                    # above user password in plain text
                    password: ${AUTHELIA_LDAP_PW}
            notifier:
                # smtp setup (example is gmail)
                smtp:
                    address: smtp://${AUTHELIA_SMTP_HOST}:587
                    username: ${AUTHELIA_SMTP_USER}
                    password: ${AUTHELIA_SMTP_PW}
                    sender: Authelia Admin <no-reply@${DOMAIN_0}>
                    tls:
                        server_name: ${AUTHELIA_SMTP_HOST}
            access_control:
                rules:
                    #Rule for API endpoints
                    - domain: "*.${DOMAIN_0}"
                      policy: bypass
                      resources:
                          - "^/api([/?].*)?$"
                          - "^/api([/?].*)?$"
                          - "^/identity.*$"
                          - "^/triggers.*$"
                          - "^/meshagents.*$"
                          - "^/meshsettings.*$"
                          - "^/agent.*$"
                          - "^/control.*$"
                          - "^/meshrelay.*$"
                          - "^/wl.*$"
                    #Rule for guacamole
                    - domain:
                          - guac.${DOMAIN_0}
                      policy: one_factor
                      subject:
                          - group:access_guacamole
                    #Rule for most publicly accessed apps
                    - domain:
                          - plex.${DOMAIN_0}
                          - kitchen.${DOMAIN_0}
                          - code.${DOMAIN_0}
                      policy: one_factor
                      subject:
                          - group:users
                    #Catch-All for Admin users
                    - domain:
                          - "*.${DOMAIN_0}"
                          - ${DOMAIN_0}
                      policy: two_factor
                      subject: "group:admin"
            password_policy:
                standard:
                    enabled: true
                    min_length: 16
                    max_length: 0
                    require_uppercase: true
                    require_lowercase: true
                    require_number: true
                    require_special: true
        workload:
            main:
                replicas: 2
                strategy: RollingUpdate
                podSpec:
                    containers:
                        main:
                            env:
                                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
                                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
                                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_ENCRYPTION_KEY}
        cnpg:
            main:
                backups:
                    credentials: aws
                    enabled: true
                    retentionPolicy: "14d"
                cluster:
                    singleNode: true
                mode: recovery
                monitoring:
                    enablePodMonitor: true
                password: ${AUTHELIA_DB_PW}
                recovery:
                    credentials: aws
                    enabled: true
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                integrations:
                    traefik:
                        enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: auth.${DOMAIN_0}
                      paths:
                          - path: /
                            pathType: Prefix
        persistence:
            config:
                volsync:
                    - credentials: aws
                      dest:
                          enabled: true
                      name: authelia-config
                      src:
                          enabled: true
                      type: restic
        resources:
            requests: # TEMP UNTIL CPU UPGRADE
                cpu: 50m
