apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-proxmox
    namespace: external-proxmox
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 16.14.15
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: external-proxmox
    values:
        TZ: Europe/Berlin
        release_name: external-proxmox
        service:
            main:
                type: ExternalIP
                externalIP: "${EXTERNAL_PROXMOX}"
                ports:
                    main:
                        protocol: https
                        port: 8006
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                annotations:
                    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                integrations:
                    traefik:
                        enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                hosts:
                    - host: prox.${DOMAIN_0}
