apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: unpackerr
    namespace: unpackerr
spec:
    interval: 15m
    chart:
        spec:
            chart: unpackerr
            version: 16.14.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: unpackerr
    values:
        TZ: Europe/Berlin
        credentials:
            aws:
                type: s3
                accessKey: ${AWS_ACCESS_KEY}
                bucket: ${AWS_BUCKET}
                encrKey: ${AWS_ENCR_KEY}
                secretKey: ${AWS_SECRET_KEY}
                url: ${AWS_URL}
#        ingress:
#            main:
#                enabled: true
#                ingressClassName: internal
#                integrations:
#                    traefik:
#                        enabled: false
#                    certManager:
#                        enabled: true
#                        certificateIssuer: domain-0-le-prod
#                hosts:
#                    - host: unpackerr.${DOMAIN_0}
#                      paths:
#                          - path: /
#                            pathType: Prefix
